### ISSUE TITLE
TC "networking Both Pods are on the Default network" marks test as passed instead of skip

### ISSUE THREAD

**Issue by kononovn** [test-network-function/test-network-function#416]
TC "networking Both Pods are on the Default network" marks test as passed instead of skipping it when label test-network-function.com/skip_connectivity_tests is present. 

Reproduction steps:

Namespace:
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: networking-tests
  name: networking-tests
```

Deployment:
---
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: networkingput
  namespace: networking-tests
spec:
  replicas: 2
  selector:
    matchLabels:
      app: networkingput
  template:
    metadata:
      labels:
        app: networkingput
        networking-test/tests: testing
        test-network-function.com/skip_connectivity_tests: ""
      name: networkingput
    spec:
      containers:
        - command: [ "/bin/bash", "-c", echo 'logs' && tail -f /dev/null" ]
          image: quay.io/centos/centos:8
          name: put
```

Tnf-config:
```
targetNameSpaces:
  - name: networking-tests
targetPodLabels:
  - prefix: networking-test
    name: tests
    value: testing
certifiedcontainerinfo:
  - name: nginx-116
    repository: rhel8
certifiedoperatorinfo:
  - name: etcd
    organization: community-operators
```

Step 1: Create namespace
        Create namespace:
            > oc create -f namespace.yml
                namespace/networking-tests created
        Validation:
            > oc get ns networking-tests
            NAME               STATUS   AGE
            networking-tests   Active   2m32s

 Step 2: Create deployment
        Create test deployment
            > oc create -f deployment_2_pods_no_ping_bin.yml
                deployment.apps/networkingput created
        Validation:
            > oc get deployment networkingput -n networking-tests
            NAME            READY   UP-TO-DATE   AVAILABLE   AGE
            networkingput   2/2     2            2           3m33s

Step 3: Set environment variable
        export environment variables
            > export TNF_PARTNER_NAMESPACE=networking-tests
            > export TNF_SKIP_SUITES='Multus|nodePort'
        Validation:
            > env | grep TNF
            TNF_PARTNER_NAMESPACE=networking-tests
            TNF_SKIP_SUITES='Multus|nodePort'
Step 4: Create tnf_config directory
        Creatre directory
            > mkdir /tmp/tnf_config
        Validation:
            > file /tmp/tnf_config
            /tmp/tnf_config: directory

Step 5: Prepare tnf_config.yml
        Copy attached tnf_config.yml to /tmp/tnf_config directory 
            > cp tnf_config.yml /tmp/tnf_config/
        Validation
            > ls -l /tmp/tnf_config/
            total 8
            -rw-rw-r--. 1 username groupname 1860 Oct 25 15:48 tnf_config.yml

Step 6: Prepare report directory
        Creatre directory
            > mkdir /tmp/tnf
        Validation:
            > file /tmp/tnf
            /tmp/tnf directory

run-test:
`    ./run-tnf-container.sh -k /tmp/artifacts/config -t /tmp/tnf_config -o /tmp/tnf/ -i quay.io/testnetworkfunction/test-network-function:unstable -f networking`

Test passed instead of skip:

• [SLOW TEST:9.068 seconds]
networking
/usr/tnf/tnf-src/test-network-function/networking/suite.go:49
  Both Pods are on the Default network
  /usr/tnf/tnf-src/test-network-function/networking/suite.go:57
    when Testing network connectivity
    /usr/tnf/tnf-src/test-network-function/networking/suite.go:73
      networking-icmpv4-connectivity
      /usr/tnf/tnf-src/test-network-function/networking/suite.go:75
------------------------------

Ran 1 of 3 Specs in 9.069 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 2 Skipped
[logs.txt](https://github.com/test-network-function/test-network-function/files/7428472/logs.txt)
